const actions = {
    INCREMENT_VALUE: 'INCREMENT_VALUE',
    DECREMENT_VALUE: 'DECREMENT_VALUE',
    INCREMENT_VALUE_SUCCESS: 'INCREMENT_VALUE_SUCCESS',
    INCREMENT_VALUE_FAILED: 'INCREMENT_VALUE_FAILED',
    DECREMENT_VALUE_SUCCESS: 'DECREMENT_VALUE_SUCCESS',
    DECREMENT_VALUE_FAILED: 'DECREMENT_VALUE_FAILED',
}

export default actions;

